Merge `membrane-webrtc-ios` into `ios-client-sdk`
fishjam-dev/ios-client-sdk pull request #15
Opened 2024-04-26 13:22 UTC by mironiasty

This PR is merging logic from `membrane-webrtc-ios` into this repository. So we can keep only one SDK for iOS.

2024-05-08 15:09 UTC, karkakol requested changes
`Membrane.podspec` file is missing. It should be included in this PR. 

I am wandering if installing pod from branch would be possible with this repo structure. This is a good functionality and if possible we should keep it.

2024-05-09 09:39 UTC, mironiasty commented on JellyfishClientDemo/JellyfishClientDemo/ContentViewController.swift
> +    func onTrackReady(ctx: JellyfishTrackContext) {
There is a conflict, as `TrackContext` is defined in `membrane-webrtc-ios` and `ios-client-sdk`. So I had to rename one of them

2024-05-09 09:40 UTC, mironiasty commented on Sources/JellyfishClientSdk/JellyfishClientInternal.swift
>          listener.onPeerJoined(peer: endpoint)
Same answer as above - great idea for new PR

2024-05-09 09:42 UTC, mironiasty commented on Sources/MembraneRTC/Media/SoundDetection.swift
> +        return Int(20 * log10(Double(maxAmplitude) / 1.0))
I have no idea. You can ask author:
https://github.com/jellyfish-dev/membrane-webrtc-ios/pull/47/files#diff-a094b671d8546e3750074840d40478f272c03ed84c77e819dc5b71e0d7767e02R211

2024-05-09 12:38 UTC, mironiasty commented
> Membrane.podspec file is missing. It should be included in this PR.

I've added podspec file to the repo. But to fully validate it, we should create cocoapod package out of this repo. Which is a scope of separate ticket.

2024-05-10 11:22 UTC, karkakol commented on JellyfishClientDemo/JellyfishClientDemo/ContentViewController.swift
> +    func onTrackReady(ctx: JellyfishTrackContext) {
JellyfishTrackContext is simple wrapper on TrackContext. This can be ease changed. Do it in this PR or create ticket to change it.

2024-05-10 11:24 UTC, karkakol commented on JellyfishClientDemo/JellyfishClientDemo/ContentViewController.swift
> +    func onJoined(peerID: String, peersInRoom: [Endpoint]) {
Let it be. Lets create task for it.

2024-05-10 11:37 UTC, karkakol requested changes
Greate you added podspec file. Now in podfile of ios app we can add:
<img width="955" alt="image" src="https://github.com/jellyfish-dev/ios-client-sdk/assets/70136588/f61c4d0c-c823-4833-a328-dbb8f465d559">
This makes testing much simpler because there is no need to release to cocoapods in testing purposes.

2024-05-10 13:52 UTC, mironiasty commented on JellyfishClientDemo/JellyfishClientDemo/ContentViewController.swift
> +    func onTrackReady(ctx: JellyfishTrackContext) {
I would argue on definition of 'easy changed' here. Anyway, let's do it in separate PR (EX-485)

2024-05-10 14:07 UTC, karkakol approved these changes
👍

2024-05-10 14:59 UTC, merged